// Utilities
import { defineStore } from "pinia";
import { ref } from "vue";

export const useAppStore = defineStore("app", () => {
  const msg = ref({
    plane: [{
      title:"标题1...标题1...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://cdn.jsdelivr.net/gh/xdlumia/files/video-play/IronMan.mp4",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题2...标题2...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题3...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题4...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题5...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题6...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题7...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题8...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题9...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题10...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    }
  ],
  three: [{
      title:"标题1...标题1...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题2...标题2...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题3...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    }],
    isometric: [{
      title:"标题1...标题1...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题2...标题2...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题3...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    }],
    motion: [{
      title:"标题1...标题1...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题2...标题2...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    },
    {
      title:"标题3...标题3...",
      subTitle:["标签1","标签3","标签4","标签4"],
      src:"https://picsum.photos/512/128?random",
      details:"这里是一段关于视频的介绍，对视频的主要内容、技术亮点等进行简要阐述。"
    }],
  });
  return { msg };
});
